apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  type: NodePort
  ports:
  - port: 8080
    name: redis
    targetPort: 8080
  selector:
    app: worker
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
        role: master
        tier: backend
    spec:
      containers:
      - name: worker
        image: gcr.io/bright-primacy-140715/worker:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080