
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
        role: master
        tier: backend
    spec:
      containers:
      - name: worker
        image: gcr.io/dta-beta-198020/worker:latest
        resources:
          requests:
            cpu: "0.1"
            memory: 100Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  type: NodePort
  ports:
  - port: 8080
    name: worker
    targetPort: 8080
  selector:
    app: worker